### ISSUE TITLE
Using pre-trained model in training doesn't work

### ISSUE THREAD

**Issue by kilsen512** [hx173149/C3D-tensorflow#10]
When I want to use the sports1m_finetuning_ucf101.model when training on the UCF-101 data set, I receive the following error:
```
NotFoundError (see above for traceback): Tensor name "var_name/bc3a/Adam" not found in checkpoint files ./sports1m_finetuning_ucf101.model
         [[Node: save/RestoreV2_86 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_86/tensor_names, save/RestoreV2_86/shape_and_slices)]]
         [[Node: save/RestoreV2_9/_5 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_793_save/RestoreV2_9", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
```

Python running on Windows 10:
`Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]`
`tensorflow-gpu (0.12.0rc0)`

Thanks!

**Comment by hx173149** [comment]
When you declare the saver you, did you used like this?`saver = tf.train.Saver(weights.values() + biases.values())`, if you write it like this format, the saver will not find the **XXX/Adam** virable, the saver just find the variables in weights and biases.

**Comment by kilsen512** [comment]
Okay, I used the pre-trained model from your dropbox. Thanks!

**Comment by geroge-gao** [comment]
@kilsenp can you tell me how you solved the problem

**Comment by kilsenp** [comment]
@geroge-gao from what I am reading, you should initialize the saver as mentioned by hx173149. Not sure why using a different pretrained model helped, but I guess thats how I solved it. Maybe this one also contained the adam variables. Sorry, don't remember precisely anymore.

**Comment by geroge-gao** [comment]
@kilsenp I am new in tensorflow, in the code provided by hx173129,the saver was intialized as `saver = tf.train.Saver(weights.values() + biases.values())`.but there occured an error.
`ValueError: The specified path: conv3d_deepnetA_sport1m_iter_1900000_TF.model is a file. Please specify only the path prefix to the checkpoint files.
`
I googled the problem,and found an issue.  [Can't load model file or directory#138](https://github.com/lengstrom/fast-style-transfer/issues/138), but it doesn't work

**Comment by kilsenp** [comment]
@geroge-gao What is your weight file named? Usually there should be multiple files and you pick the one named *.ckpt. 
Read this: https://www.tensorflow.org/programmers_guide/saved_model

**Comment by geroge-gao** [comment]
the weight file is named as "conv3d_deepnetA_sport1m_iter_1900000_TF.model",it was provided by hx173149. and could you tell me how you solve your problem? thanks for any help.

**Comment by geroge-gao** [comment]
@kilsenp the weight file is named as "conv3d_deepnetA_sport1m_iter_1900000_TF.model",it was provided by hx173149. and could you tell me how you solve your problem? thanks for any help.

**Comment by geroge-gao** [comment]
@kilsenp the weight file is named as "conv3d_deepnetA_sport1m_iter_1900000_TF.model",it was provided by hx173149. Actually I don't know how to you the pre-trained model , could you tell me how you solve your problem? thanks for any help.
