### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by didiwai** [hx173149/C3D-tensorflow#12]
Hi 
  I run your code train_c3d_ucf101.py and predict_c3d_ucf101.py, both of them have a ValueError
ValueError: Cannot feed value of shape (10, 0) for Tensor u'Placeholder:0', which has shape '(10, 16, 112, 112, 3)'. And I find in train_c3d_ucf101.py, this error happend in line 232
                   `  sess.run(train_op, feed_dict={
                      images_placeholder: train_images,
                      labels_placeholder: train_labels
                      })`
 Do you have any idea why it failed? I use tensorflow 0.11.

**Comment by didiwai** [comment]
Find the error closed

**Comment by Shiny128** [comment]
Please share the procedure to solve that error.
