### ISSUE TITLE
missunderstanding about .model file type

### ISSUE THREAD

**Issue by sisgrad** [hx173149/C3D-tensorflow#127]
Hello! Just tested video inference of this repo and noticed that pretrained model have .model format, not tensorflow .pb file.  My question is - which framework of DL has  .model saved model format? I have never seen this format before.

Also, I'm using C3D-Keras repo for training c3d models, and models are saving to keras .h5 format. Can I use my .h5 models to do inference in this repo, should I convert it from .h5 to .model format?

**Comment by SaadTazroute** [comment]
Same issue
