### ISSUE TITLE
Efficiency between tensorflow and caffe?

### ISSUE THREAD

**Issue by LongLong-Jing** [hx173149/C3D-tensorflow#17]
@hx173149 
Did you notice the difference in efficiency between this code and original C3D code?
During testing, the batch size of caffe code can be 30 in GTX, while the batch size for this code is 15. When adding the batch size, the code will report 'Out of Memory' error. Can you tell me you GPU configuration and batch size during training? Thanks!

**Comment by hx173149** [comment]
Hi @LongLong-Jing 
Yes, maybe there have some points to optimize the efficiency.
