### ISSUE TITLE
how to convert trained C3D model to tensorflow version

### ISSUE THREAD

**Issue by jiang2764** [hx173149/C3D-tensorflow#19]
Can you share your code about converting sport1m caffe model to its tensorflow version?　I tried to use this code https://github.com/ethereon/caffe-tensorflow, which did not support the video data layer. Thanks. @hx173149 @chuckcho

**Comment by hx173149** [comment]
Hi @jiang2764 
I am sorry, the convert code has been used too long time ago and I can not find the code now.
