### ISSUE TITLE
about the machine information

### ISSUE THREAD

**Issue by BoPang1996** [hx173149/C3D-tensorflow#22]
Hi，

I have used this C3D model to train a classifier, but, I get some problem that I cannot run this code：
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:0c:00.0)
E tensorflow/stream_executor/cuda/cuda_driver.cc:1177] could not synchronize on CUDA context: CUDA_ERROR_MISALIGNED_ADDRESS :: No stack trace available
E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_MISALIGNED_ADDRESS
F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:198] Unexpected Event status: 1
F tensorflow/core/common_runtime/gpu/gpu_util.cc:370] GPU sync failed
Aborted (core dumped)

I find that the usage of the card is 100%. 
![image](https://user-images.githubusercontent.com/17980676/27227653-ea62b3c4-52d6-11e7-822e-18627c0631f1.png)
May I ask which card you used to run this code？

**Comment by hx173149** [comment]
Hi @BoPang1996 
I have 4 GPU cards in my machine.
