### ISSUE TITLE
Question about the network architecture

### ISSUE THREAD

**Issue by yzldw333** [hx173149/C3D-tensorflow#27]
Thank u for your share. I have some questions that I wrote the codes to convert caffemodel to other file with pickle in python, and I wrote the codes to read the parameters using the file I created. At that time, I found your network architecture is not the same as standard C3D network, like conv3 conv4, and fc layer. Is that your personal change to make network performance better ?  How about the result ?

**Comment by hx173149** [comment]
Hi @yzldw333 
Can you explain more detail about the difference? I think my network architecture is same as the caffe code's version. And the TF's model is transferred from the caffe's model.
