### ISSUE TITLE
no volume_mean or mean_value ?

### ISSUE THREAD

**Issue by simplysimleprob** [hx173149/C3D-tensorflow#3]
Hi,

First of all, thank you for sharing your code. It's a great help for my work.
I was wondering whether we need to subtract volume_mean (or mean_value) from input video frames?
It seems like the original Caffe-based implementation do apply mean substraction.

What are your thoughts on this? Do you think this will impact the accuracy?
Thank you for your help.

**Comment by hx173149** [comment]
hello simplysimleprob,
Yes, the Caffe-based version have do the mean subtraction and did not apply normalization for every pixel.
I used to do these pre process in TF work, but it didn't make a big promotion, maybe you can try it yourself.

**Comment by hx173149** [comment]
@simplysimleprob I have transferred the sports1M model from caffe version to tf version,and added the mean file too.
