### ISSUE TITLE
input_data missing attribute ReadDataLabelFromFile

### ISSUE THREAD

**Issue by toddnguyen** [hx173149/C3D-tensorflow#4]
I cloned your repository, added in the UCF Dataset in the format specified in the list, looks like C3D-tensorflow/database/ucf101/train/ and put the sports1m_finetuning_ucf101.model and sports1m_finetuning_ucf101.model and crop_mean.npy files in the root (in C3D-tensorflow folder).

When I run "python train_c3d_ucf101.py" I get this error:\

```
I tensorflow/core/common_runtime/simple_placer.cc:819] var_name/wc1/Initializer/random_uniform/shape: /job:localhost/replica:0/task:0/cpu:0
Adam_1/value: /job:localhost/replica:0/task:0/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:819] Adam_1/value: /job:localhost/replica:0/task:0/cpu:0
global_step/Initializer/Const: /job:localhost/replica:0/task:0/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:819] global_step/Initializer/Const: /job:localhost/replica:0/task:0/cpu:0
Traceback (most recent call last):
  File "train_c3d_ucf101.py", line 224, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train_c3d_ucf101.py", line 221, in main
    run_training()
  File "train_c3d_ucf101.py", line 198, in run_training
    train_images,train_labels = input_data.ReadDataLabelFromFile('list/train.list',FLAGS.batch_size*gpu_num)
AttributeError: 'module' object has no attribute 'ReadDataLabelFromFile'
```

Do you know what would cause this issue? I also have no GPU, not sure if that would cause an issue.

It looks like input_data has the "ReadDataLabelFromFile_16" but no "ReadDataLabelFromFile". Is there an updated input_data.py file?

Thanks

**Comment by hx173149** [comment]
Thanks for telling me this bug,I forget to update the file inputdata.py, I have fixed it.

**Comment by toddnguyen** [comment]
Thank you for the quick response, I had one more question, on line 198 it says:
`      train_images,train_labels = input_data.ReadDataLabelFromFile('list/train.list',FLAGS.batch_size*gpu_num)
`

I made a copy of the list train_ucf101.trainVideos and renamed it to train.list, will that work? Or was there another train.list that you used?

**Comment by hx173149** [comment]
@toddnguyen 
1. The UCF101 dataset should be download first
2. Decode each video with 5FPS to a directory respectively
3. Make the list format like mine
