### ISSUE TITLE
Error in running Random_clip_valid.py

### ISSUE THREAD

**Issue by hajra1995** [hx173149/C3D-tensorflow#88]
I am trying to run Random_clip_valid.py using spyder IDE. But when ever I run that file an error is retrieved:
```
File "E:/MS_Research_work/Python/C3D-tensorflow/C3D-tensorflow-1.0/Random_clip_valid.py", line 12, in <module>
    from tqdm import  tqdm

ModuleNotFoundError: No module named 'tqdm'
```
whereas, I have already installed 'tqdm' module version 4.24 in tensorflow environment. I am using tensorflow version 1.1 and python version 3.5.5. I can not figure out the reason behind this error. I am beginner in python

**Comment by rocksyne** [comment]
try 
Python 3

> sudo pip install tqdm 

Python 2

> sudo pip install tqdm

**Comment by hajra1995** [comment]
I am using windows 10, sudo commands only work on Linux

**Comment by rocksyne** [comment]
If you are using anaconda,  open the Anaconda prompt and install pip using 

> conda install pip

then you can use pip to install tqdm by doing

> pip install tqdm

Aside these, there is no other way I know about. If I find anything else, I will share with you.

**Comment by hajra1995** [comment]
I overcame the issue, by building code in anaconda command prompt instead of spyder IDE. Thanks, for help
